# Generated by Django 5.2.15 on 2026-06-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='target_companies',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
